
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Chapter 2 - AWS Security Foundations
  Provisions IAM user, KMS key, CloudTrail, AWS Config, GuardDuty, and Security Hub.

Parameters:
  IAMUserName:
    Type: String
    Default: ch2-user
    Description: Name of the IAM user to create.

  TrailName:
    Type: String
    Default: ch2-trail
    Description: Name of the CloudTrail trail.

  ConfigRecorderName:
    Type: String
    Default: ch2-config-recorder
    Description: Name of the AWS Config recorder.

  ConfigDeliveryChannelName:
    Type: String
    Default: ch2-delivery-channel
    Description: Name of the AWS Config delivery channel.

Resources:

  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref IAMUserName

  IAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ch2-user-policy
      Users:
        - !Ref IAMUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "kms:*"
              - "cloudtrail:*"
              - "config:*"
              - "guardduty:*"
              - "securityhub:*"
            Resource: "*"

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "KMS key for CloudTrail encryption"
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  CloudTrailS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "ch2-cloudtrail-logs-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

  CloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Ref TrailName
      S3BucketName: !Ref CloudTrailS3Bucket
      IsLogging: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      KMSKeyId: !Ref KMSKey

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: !Ref ConfigRecorderName
      RoleARN: !GetAtt ConfigRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true

  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ch2-config-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRole

  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      Name: !Ref ConfigDeliveryChannelName
      S3BucketName: !Ref CloudTrailS3Bucket

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true

  SecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties: {}
