name: Network Firewall GitOps Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'chapter12/infrastructure/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'chapter12/infrastructure/**'

env:
  TF_VERSION: 1.6.0
  AWS_REGION: us-west-2

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::387974667323:role/GitHubActionsRoleAllRepos
        role-session-name: samplerolesession
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      working-directory: ./chapter12/infrastructure
      run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

    - name: Terraform Format
      working-directory: ./chapter12/infrastructure
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: ./chapter12/infrastructure
      run: terraform validate

    - name: Import Network Firewall (if not already imported)
      working-directory: ./chapter12/infrastructure
      if: github.event_name == 'pull_request'
      run: |
        FIREWALL_EXISTS=$(terraform state list | grep -w "aws_networkfirewall_firewall.main" || echo "notfound")
        POLICY_EXISTS=$(terraform state list | grep -w "aws_networkfirewall_firewall_policy.AllowAllTrafficPolicy" || echo "notfound")

        if [ "$FIREWALL_EXISTS" = "notfound" ]; then
          echo "Importing Network Firewall..."
          terraform import aws_networkfirewall_firewall.main \
            arn:aws:network-firewall:us-west-2:387974667323:firewall/SecureInfraFirewall
        else
          echo "Firewall already imported. Skipping..."
        fi

        if [ "$POLICY_EXISTS" = "notfound" ]; then
          echo "Importing Firewall Policy..."
          terraform import aws_networkfirewall_firewall_policy.AllowAllTrafficPolicy \
            arn:aws:network-firewall:us-west-2:387974667323:firewall-policy/AllowAllTrafficPolicy
        else
          echo "Firewall Policy already imported. Skipping..."
        fi

    - name: Terraform Plan
      working-directory: ./chapter12/infrastructure
      run: terraform plan -no-color
      if: github.event_name == 'pull_request'

    - name: Terraform Apply
      working-directory: ./chapter12/infrastructure
      run: terraform apply -auto-approve
      if: github.event_name == 'push'
